Repository metabrainz/picard-docs, pull requests merged in 2021-03, with the labels that each got.

#87 Update to version 2.6b1
  _locale/fr/LC_MESSAGES/appendices/tag_mapping.po
  _locale/fr/LC_MESSAGES/config/options_fingerprinting.po
  _locale/fr/LC_MESSAGES/config/options_tags_compatibility_id3.po
  _locale/fr/LC_MESSAGES/variables/tags_basic.po
  _locale/fr/LC_MESSAGES/variables/variables_basic.po
  appendices/tag_mapping.rst
  conf.py
  config/options_fingerprinting.rst
  config/options_tags_compatibility_id3.rst
  tag_mapping.py
  variables/tags_basic.rst
  variables/variables_basic.rst
Labels: documentation

#86 Update description of "Use the first image type..." option setting.
  _locale/fr/LC_MESSAGES/config/options_cover_art_archive.po
  _locale/fr/LC_MESSAGES/config/options_location.po
  config/images/options-cover-caa.png
  config/images/options-cover.png
  config/options_cover_art_archive.rst
  config/options_location.rst
Labels: bug, documentation

#89 Document new interface option to select light or dark theme
  _locale/fr/LC_MESSAGES/config/options_interface.po
  _locale/fr/LC_MESSAGES/config/options_interface_colors.po
  config/images/options-interface.png
  config/options_interface.rst
  config/options_interface_colors.rst
Labels: documentation, enhancement

#91 Set Artists ID3 tag to upper case
  _locale/fr/LC_MESSAGES/appendices/tag_mapping.po
  appendices/tag_mapping.rst
  tag_mapping.py
Labels: bug, documentation

#93 Appendix: Keyboard shortcuts help
  appendices/keyboard_shortcuts.rst
  index.rst
Labels: documentation, enhancement
