Repository metabrainz/picard-docs, pull requests merged in 2022-05, with the labels that each got.

#166 Add saving and restoring configuration file options
  config/images/options-maintenance.png
  config/options_maintenance.rst
Labels: documentation

#167 Add information about `Show other album versions...` dialog
  usage/images/lookup_other_matching.png
  usage/retrieve_lookup_steps.txt
Labels: documentation, enhancement

#168 Updated to Sphinx 4.5
  requirements.txt
Labels: setup

#170 Changes to clean up epub output
  _static/Picard_logo_no_text.svg
  _static/epub_cover.png
  _templates/epub-cover.html
  appendices/pdf_appendices.rst
  conf.py
  config/configuration.rst
  config/options_advanced.rst
  config/options_cdlookup.rst
  config/options_cover.rst
  config/options_filerenaming.rst
  config/options_interface.rst
  config/options_maintenance.rst
  config/options_metadata.rst
  config/options_scripting.rst
  config/options_tags.rst
  epub.rst
  extending/extending.rst
  extending/scripting.rst
  faq/faq.rst
  functions/list_by_name.rst
  functions/list_by_type.rst
  getting_started/pdf_starting.rst
  index.rst
  troubleshooting/pdf_troubleshooting.rst
  troubleshooting/troubleshooting.rst
  tutorials/tutorials.rst
  usage/other.rst
  usage/retrieve.rst
  usage/retrieve_lookup_cd_steps.txt
  usage/using.rst
  variables/variables.rst
  workflows/workflows.rst
Labels: documentation, format, setup
